# Generated by Django 3.1.5 on 2021-01-24 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseStat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Stat',
            fields=[
                ('id', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('name_txt', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('name_txt', models.CharField(max_length=200)),
                ('height', models.FloatField()),
                ('weight', models.FloatField()),
                ('bases_stats', models.ManyToManyField(through='pokemons.BaseStat', to='pokemons.Stat')),
            ],
        ),
        migrations.AddField(
            model_name='basestat',
            name='pokemon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokemons.pokemon'),
        ),
        migrations.AddField(
            model_name='basestat',
            name='stat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokemons.stat'),
        ),
    ]
