# Generated by Django 3.1.5 on 2021-01-24 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemons', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='basestat',
            name='base_stat',
            field=models.IntegerField(default=0),
        ),
    ]
