# Generated by Django 3.1.5 on 2021-01-24 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pokemons', '0002_basestat_base_stat'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ability',
            fields=[
                ('id', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('name_txt', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Egg_Group',
            fields=[
                ('id', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('name_txt', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Habitat',
            fields=[
                ('id', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('name_txt', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='PokemonType',
            fields=[
                ('id', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('name_txt', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Specie',
            fields=[
                ('id', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('name_txt', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=200)),
                ('color', models.CharField(max_length=200)),
                ('base_happiness', models.FloatField()),
                ('capture_rate', models.FloatField()),
                ('egg_group', models.ManyToManyField(to='pokemons.Egg_Group')),
                ('habitat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokemons.habitat')),
            ],
        ),
        migrations.AddField(
            model_name='pokemon',
            name='ability',
            field=models.ManyToManyField(to='pokemons.Ability'),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='type',
            field=models.ManyToManyField(to='pokemons.PokemonType'),
        ),
    ]
