# Generated by Django 3.1.5 on 2021-01-24 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokemons', '0004_pokemon_specie'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Egg_Group',
            new_name='EggGroup',
        ),
    ]
