# Generated by Django 3.1.5 on 2021-01-24 19:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pokemons', '0005_auto_20210124_1840'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvolutionClain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clain_id', models.IntegerField()),
                ('min_level', models.IntegerField()),
                ('Specie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokemons.specie')),
                ('evolution_from', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evolution_from', to='pokemons.specie')),
                ('evolution_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evolution_to', to='pokemons.specie')),
            ],
        ),
    ]
