# Generated by Django 3.1.5 on 2021-01-24 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokemons', '0006_evolutionclain'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evolutionclain',
            old_name='Specie',
            new_name='specie',
        ),
    ]
