# Generated by Django 3.1.5 on 2021-01-24 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokemons', '0007_auto_20210124_2012'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EvolutionClain',
            new_name='EvolutionChain',
        ),
        migrations.RenameField(
            model_name='evolutionchain',
            old_name='clain_id',
            new_name='chain_id',
        ),
    ]
