# Generated by Django 3.1.5 on 2021-01-24 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemons', '0008_auto_20210124_2019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evolutionchain',
            name='min_level',
            field=models.IntegerField(null=True),
        ),
    ]
