# Generated by Django 3.1.5 on 2021-01-24 21:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pokemons', '0011_auto_20210124_2128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evolutionchain',
            name='specie',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='pokemons.specie'),
        ),
    ]
