# Generated by Django 3.1.5 on 2021-01-25 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemons', '0012_auto_20210124_2129'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='picture_url',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
