# Generated by Django 3.1.5 on 2021-01-25 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokemons', '0013_pokemon_picture_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specie',
            name='type',
        ),
    ]
